//regexp ["$1", "$2"],

let g_allcombos = 
[
["Air",   0],
["Earth", 1],
["Fire",  2],
["Water", 3],
["Wind", "Air + Air"],
["Lightning", "Air + Fire"],
["Fog", "Air + Water"],
["Stone", "Earth + Fire"],
["Swamp", "Earth + Water"],
["Alcohol", "Fire + Water"],
["Volcano", "Earth + Fire + Fire"],
["Sedimentary Rock", "Earth + Stone"],
["Steam", "Fire + Fog"],
["Clouds", "Fog + Water"],
["Metals", "Stone + Fire"],
["Salt Water", "Stone + Water"],
["Sand", "Stone + Wind"],
["Amino Acids", "Swamp + Lightning"],
["NO2", "Air + Air + Lightning"],
["Hydrothermal Vein", "Earth + Volcano + Water"],
["Bacteria", "Amino Acids + Swamp"],
["Rain", "Clouds + Water"],
["Glass", "Fire + Sand"],
["Minerals", "Hydrothermal Vein + Earth"],
["Fulgurite", "Lightning + Sand"],
["Lead", "Metals + Fire"],
["Electricity", "Metals + Lightning"],
["Rust", "Metals + Water"],
["HNO3", "NO2 + Water"],
["Salt", "Salt Water + Air"],
["Clay", "Sand + Swamp"],
["Gold", "Sedimentary Rock + Metals"],
["Silver", "Sedimentary Rock + Metals"],
["Magnet", "Stone + Metals"],
["Zinc", "Metals + Fire + Fire"],
["Cold", "Wind + Wind + Clouds"],
["Aluminum", "Metals + Fire + Fire + Fire"],
["Copper", "Metals + Fire + Fire + Fire + Fire"],
["Iron", "Metals + Fire + Fire + Fire + Fire"],
["Chromium", "Metals + Fire + Fire + Fire + Fire + Fire + Fire"],
["Tungsten", "Metals + Fire + Fire + Fire + Fire + Fire + Fire + Fire"],
["Mutating Bacteria", "Alcohol + Bacteria"],
["Cells", "Bacteria + Bacteria"],
["Stromatolites", "Bacteria + Stone"],
["Algae", "Bacteria + Water"],
["Brick", "Clay + Fire"],
["Bronze", "Copper + Lead"],
["Brass", "Copper + Zinc"],
["CuZn Battery", "Copper + Zinc"],
["Viruses", "Earth + Bacteria"],
["Cinnabar", "Earth + Minerals"],
["Sulfur", "Earth + Minerals"],
["Hydrogen", "Electricity + Water"],
["Oxygen", "Electricity + Water"],
["Lightbulb", "Glass + Tungsten"],
["Nitric Acid", "HNO3 + Water"],
["Steel", "Iron + Chromium"],
["Graphite", "Minerals + Volcano"],
["Mineral Water", "Minerals + Water"],
["Snow", "Rain + Cold"],
["Thunderstorm", "Rain + Lightning"],
["Sandglass", "Sand + Glass"],
["Ice", "Water + Cold"],
["Chlorine", "Fire + Salt + Electricity"],
["Sodium", "Fire + Salt + Electricity"],
["Compass", "Glass + Magnet + Metals"],
["Plankton", "Cells + Water"],
["Mercury", "Cinnabar + Fire"],
["Acid Rain", "Clouds + Nitric Acid"],
["Flashlight", "CuZn Battery + Lightbulb"],
["Moss", "Earth + Algae"],
["Chemical Rubbish", "Fire + CuZn Battery"],
["HCL", "Hydrogen + Chlorine"],
["HNO2", "Hydrogen + NO2"],
["Lead Oxide", "Lead + Oxygen"],
["Glowing Lightbulb", "Lightbulb + Electricity"],
["Sulfur Dioxide", "Oxygen + Sulfur"],
["Sodium Hydroxide", "Sodium + Water"],
["Fungi", "Swamp + Algae"],
["Liquid Oxygen", "Water + Oxygen"],
["Grass", "Earth + Moss"],
["Arthropods", "Earth + Plankton"],
["Hydrochloric Acid", "HCL + Water"],
["Nitrous Acid", "HNO2 + Water"],
["Dewar Flask", "Liquid Oxygen + Aluminum"],
["Thermometer", "Mercury + Glass"],
["Amalgam", "Mercury + Silver"],
["Fish", "Plankton + Algae"],
["Corals", "Plankton + Stone"],
["Molluscs", "Plankton + Swamp"],
["Jellyfish", "Plankton + Water"],
["Starfish", "Sand + Plankton"],
["Fertilizer", "Sodium Hydroxide + Nitric Acid"],
["Sodium Hydroxide Solution", "Sodium Hydroxide + Water"],
["Sulfur Trioxide", "Sulfur Dioxide + Oxygen"],
["Fern", "Swamp + Moss"],
["Sand on Glass", "Glass + Sand + Glowing Lightbulb"],
["Crystal Glass", "Lead Oxide + Fire + Sand"],
["Drunken Animal", "Alcohol + Arthropods"],
["Beetles", "Arthropods + Air"],
["Undefined Dead Lifeform", "Arthropods + Hydrochloric Acid"],
["Coral Reefs", "Corals + Corals"],
["Thermos", "Dewar Flask + Metals"],
["Millipedes", "Earth + Arthropods"],
["Shrub", "Earth + Fern"],
["Bamboo", "Earth + Grass"],
["Snails", "Earth + Molluscs"],
["Palms", "Fern + Sand"],
["Flying Fish", "Fish + Air"],
["Eel", "Fish + Electricity"],
["Amphibians", "Fish + Swamp"],
["Vegetable Waste", "Fungi + Hydrochloric Acid"],
["Mirror", "Glass + Amalgam"],
["Aquarium", "Glass + Fish"],
["Flowers", "Grass + Fern"],
["Peat", "Grass + Swamp"],
["Reed", "Grass + Water"],
["Mussels", "Molluscs + Sand"],
["Cephalopods", "Molluscs + Water"],
["Mutating Plant", "Mutating Bacteria + Fern"],
["Trilobites", "Sand + Arthropods"],
["Spiders", "Stone + Arthropods"],
["Sulfuric Acid", "Sulfur Trioxide + Water"],
["Slugs", "Swamp + Molluscs"],
["Shrimps", "Water + Arthropods"],
["Insects", "Air + Beetles"],
["Alien", "Amphibians + Mutating Bacteria"],
["Reptiles", "Amphibians + Sand"],
["Frogs", "Amphibians + Swamp"],
["Ammonites", "Cephalopods + Sand"],
["Octopus", "Cephalopods + Water"],
["Salamanders", "Earth + Amphibians"],
["Trees", "Earth + Flowers"],
["Coal", "Earth + Peat"],
["Worms", "Earth + Slugs"],
["Animal Fossil", "Earth + Undefined Dead Lifeform"],
["Cactus", "Flowers + Sand"],
["Orchids", "Fungi + Flowers"],
["Terrarium (A)", "Glass + Amphibians"],
["Search Light", "Glowing Lightbulb + Mirror"],
["Spider Web", "Grass + Spiders"],
["Tropics", "Palms + Rain"],
["Crabs", "Sand + Shrimps"],
["Scorpions", "Sand + Spiders"],
["Methane", "Vegetable Waste + Earth"],
["Vegetable Oil", "Vegetable Waste + Stone"],
["Compost", "Vegetable Waste + Vegetable Waste"],
["Hedge", "Shrub + Shrub + Shrub"],
["Extremely Infectious Alien", "Alien + Viruses"],
["Wormy Compost", "Compost + Worms"],
["Limestone", "Earth + Ammonites"],
["Toads", "Earth + Frogs"],
["Ants", "Earth + Insects"],
["Lizards", "Earth + Reptiles"],
["Flies", "Fungi + Insects"],
["Exhibit", "Glass + Animal Fossil"],
["Terrarium (R)", "Glass + Reptiles"],
["Mammals", "Ice + Reptiles"],
["Bees", "Insects + Flowers"],
["Stick Insects", "Insects + Trees"],
["Dragonflies", "Insects + Water"],
["Chloroform", "Methane + Chlorine"],
["Dinosaurs", "Reptiles + Sand"],
["Crocodiles", "Reptiles + Water"],
["Sandworms", "Sand + Worms"],
["Indigofera", "Shrub + Tropics"],
["Snakes", "Swamp + Reptiles"],
["Liana", "Trees + Grass"],
["Wooden Fragments", "Trees + Lightning"],
["Forest", "Trees + Trees"],
["Hevea", "Trees + Tropics"],
["Robot", "Metals + Alien + CuZn Battery"],
["Stove", "Stone + Coal + Fire"],
["Flying Dinosaurs", "Air + Dinosaurs"],
["Bats", "Air + Mammals"],
["Kite", "Air + Snakes"],
["Honey Bee", "Bees + Flowers"],
["Poisoned Animal", "Dragonflies + Chlorine"],
["Rodents", "Earth + Mammals"],
["Butterflies", "Flies + Flowers"],
["Mosquitos", "Flies + Swamp"],
["Dying Forest", "Forest + Beetles"],
["Insectivora", "Insects + Mammals"],
["Unhydrated Lime", "Limestone + Fire"],
["Platypus", "Reptiles + Mammals"],
["Active Robot", "Robot + Alien"],
["Plesiosaurs", "Water + Dinosaurs"],
["Watermammals", "Water + Mammals"],
["Humus", "Wormy Compost + Earth"],
["Stone Axe", "Liana + Wooden Fragments + Stone"],
["Radioactivity", "Active Robot + Alien"],
["Container", "Active Robot + Metals"],
["Birds", "Air + Flying Dinosaurs"],
["Caterpillar", "Butterflies + Butterflies"],
["Rats", "Chemical Rubbish + Rodents"],
["Moles", "Earth + Insectivora"],
["Mice", "Earth + Rodents"],
["Rabbits", "Fern + Rodents"],
["Honey", "Flowers + Honey Bee"],
["Hares", "Grass + Rodents"],
["Beehive", "Honey Bee + Honey Bee"],
["Sugar Cane", "Humus + Bamboo"],
["Lettuce", "Humus + Fern"],
["Cotton", "Humus + Flowers"],
["Lint", "Humus + Flowers"],
["Mushrooms", "Humus + Fungi"],
["Cereals", "Humus + Grass"],
["Fruit Trees", "Humus + Trees"],
["Marmots", "Stone + Rodents"],
["Squirrels", "Trees + Rodents"],
["Wood", "Trees + Stone Axe"],
["Hydrated Lime", "Unhydrated Lime + Water"],
["Dolphins", "Water + Watermammals"],
["Drilling Rig", "Active Robot + Metals + Earth"],
["Freezer", "Active Robot + Metals + Ice"],
["Incomplete Boiler", "Active Robot + Water + Metals"],
["Steam Turbine", "Metals + Steam + Active Robot"],
["Wind Turbine", "Metals + Wind + Active Robot"],
["Whales", "Watermammals + Water + Water"],
["UFO", "Active Robot + Glass + Metals + Air"],
["Water Turbine", "Water + Water + Metals + Active Robot"],
["Hummingbirds", "Birds + Flowers"],
["Cocoon", "Caterpillar + Trees"],
["Grains", "Cereals + Metals"],
["Straw", "Cereals + Metals"],
["Hamsters", "Cereals + Rodents"],
["Rice", "Cereals + Water"],
["Chemical Waste", "Chemical Rubbish + Container"],
["Electric Boiler", "CuZn Battery + Incomplete Boiler"],
["Borehole", "Earth + Drilling Rig"],
["Frozen Alien", "Freezer + Alien"],
["Fruits", "Fruit Trees + Wormy Compost"],
["Cement", "Hydrated Lime + Clay"],
["Ironwood", "Iron + Wood"],
["Tortoises", "Lettuce + Reptiles"],
["Bear", "Mammals + Honey"],
["Oxygen Container", "Oxygen + Container"],
["Uranium", "Radioactivity + Metals"],
["Sugar", "Sugar Cane + Metals"],
["Waterbirds", "Water + Birds"],
["Termites", "Wood + Ants"],
["Woodpeckers", "Wood + Birds"],
["Tools", "Wood + Metals"],
["Beavers", "Wood + Rodents"],
["Incomplete Building", "Wood + Stone"],
["Boat", "Wood + Water"],
["Woodworms", "Wood + Worms"],
["Atom Battery", "Active Robot + Radioactivity + CuZn Battery"],
["Plutonium", "Radioactivity + Radioactivity + Metals"],
["Cellulose", "Water + Sulfuric Acid + Wood"],
["Ash", "Wood + Fire + Fire"],
["Seagulls", "Air + Waterbirds"],
["Carbon Dioxide", "Ash + Nitric Acid"],
["Potassium Nitrate", "Ash + Nitric Acid"],
["Panda", "Bear + Bamboo"],
["Wax", "Beehive + Tools"],
["Down", "Birds + Tools"],
["Hovercraft", "Boat + Air"],
["Submarine", "Boat + Oxygen Container"],
["Draw Well", "Borehole + Water"],
["Needle", "Cactus + Tools"],
["Silk", "Cocoon + Tools"],
["Cotton Wool", "Cotton + Tools"],
["Fiber", "Cotton + Tools"],
["Banana", "Fruits + Grass"],
["Juice", "Fruits + Stone"],
["Chickens", "Grains + Birds"],
["Granary", "Grains + Incomplete Building"],
["Black Lead", "Graphite + Tools"],
["Polar Bear", "Ice + Bear"],
["Penguins", "Ice + Waterbirds"],
["Nuclear Boiler", "Incomplete Boiler + Uranium"],
["Museum", "Incomplete Building + Exhibit"],
["Scuba", "Oxygen Container + Water"],
["Anvil", "Steel + Tools"],
["House", "Stove + Incomplete Building"],
["Sugar Water", "Sugar + Water"],
["Carbon", "Sulfuric Acid + Sugar"],
["Bones", "Tools + Animal Fossil"],
["Canines", "Tools + Animal Fossil"],
["Tube", "Tools + Bamboo"],
["Caoutchouc", "Tools + Hevea"],
["Indigo", "Tools + Indigofera"],
["Ducks", "Water + Waterbirds"],
["Atom Bomb", "Active Robot + Metals + Plutonium"],
["Incomplete Factory", "Electric Boiler + Brick + Stone"],
["Flour", "Grains + Stone + Stone"],
["Orangery", "Incomplete Building + Glass + Flowers"],
["Incomplete Mechanism", "Wood + Tools + Metals"],
["Monkeys", "Banana + Mammals"],
["Ornithopter", "Birds + Incomplete Mechanism"],
["Pencil", "Black Lead + Wood"],
["Ebonit", "Caoutchouc + Sulfur"],
["Rubber", "Caoutchouc + Volcano"],
["Cast Iron", "Carbon + Iron"],
["Dry Ice", "Carbon Dioxide + Cold"],
["Aerated Water", "Carbon Dioxide + Water"],
["Paper Factory", "Cellulose + Incomplete Factory"],
["Eggs", "Chickens + Grains"],
["Cotton Candy", "Cotton Wool + Sugar"],
["Yarn", "Fiber + Fiber"],
["Smoking Pipe", "Fire + Tube"],
["Sharks", "Fish + Canines"],
["Roses", "Flowers + Needle"],
["Spyglass", "Glass + Tube"],
["Village", "House + House"],
["Hydrocarbon", "Hydrogen + Carbon"],
["Jeans", "Indigo + Cotton"],
["Paint", "Indigo + Water"],
["Hedgehog", "Insectivora + Needle"],
["Wine", "Juice + Fungi"],
["Rope", "Liana + Fiber"],
["Domestic Animals", "Mammals + House"],
["Atomic Submarine", "Nuclear Boiler + Submarine"],
["Infected Animal", "Panda + Viruses"],
["Porcupines", "Rodents + Needle"],
["Cryogenic Scuba", "Scuba + Dewar Flask"],
["Soda", "Sodium Hydroxide + Carbon Dioxide"],
["Steam Engine", "Steam + Incomplete Mechanism"],
["Nuclear Power Station", "Steam Turbine + Nuclear Boiler"],
["Diamond", "Stone + Carbon"],
["Swamp Chickens", "Swamp + Chickens"],
["Saw", "Tools + Canines"],
["Conifers", "Trees + Needle"],
["Aardvark", "Tube + Mammals"],
["Tubing", "Tube + Tube"],
["Wheel", "Wood + Incomplete Mechanism"],
["ZnC Battery", "Zinc + Carbon"],
["Gun Powder", "Carbon + Sulfur + Potassium Nitrate"],
["Bakery", "Flour + Stove + Incomplete Building"],
["Forge", "Stove + Anvil + Incomplete Building"],
["Loom", "Wood + Fiber + Tools"],
["Steam Boat", "Boat + Steam Engine"],
["Caterpillar Platform", "Caterpillar + Wheel"],
["Paper", "Cellulose + Paper Factory"],
["Chicks", "Chickens + Eggs"],
["Potter’s Wheel", "Clay + Wheel"],
["New Year’s Baubles", "Conifers + Glass"],
["Cones", "Conifers + Tools"],
["Resin", "Conifers + Tools"],
["Wire", "Copper + Rope"],
["Yellow Water Toy", "Ducks + Rubber"],
["Coins", "Forge + Gold"],
["Tobacco", "Grass + Smoking Pipe"],
["Bickford Fuse", "Gun Powder + Rope"],
["Gas Field", "Hydrocarbon + Earth"],
["Oil Field", "Hydrocarbon + Earth"],
["Food Factory", "Incomplete Factory + Bakery"],
["Gear", "Incomplete Mechanism + Wheel"],
["Textile Factory", "Loom + Incomplete Factory"],
["Nuclear Waste", "Nuclear Power Station + Container"],
["Sail Plane", "Ornithopter + Air"],
["Fresco", "Paint + Hydrated Lime"],
["Wick", "Rope + Vegetable Oil"],
["Rope Ladder", "Rope + Wood"],
["Hose", "Rubber + Tube"],
["Hammerhead Sharks", "Sharks + Tools"],
["Hookah", "Smoking Pipe + Water"],
["Microscope", "Spyglass + Bacteria"],
["Toy for Rodents", "Squirrels + Wheel"],
["Pressure", "Steam + Steam Engine"],
["Flute", "Tools + Ebonit"],
["Water Pipeline", "Tubing + Water"],
["Water Wheel", "Water + Wheel"],
["Windmill", "Wheel + Incomplete Building"],
["Horn", "Wine + Animal Fossil"],
["Vinegar", "Wine + Bacteria"],
["Cart", "Wood + Wheel"],
["Textile", "Yarn + Loom"],
["Fishing Net", "Fish + Spider Web + Rope"],
["Bread", "Flour + Eggs + Fire + Water"],
["Natural Gas", "Borehole + Gas Field"],
["Oil", "Borehole + Oil Field"],
["Safe", "Coins + Container"],
["Map", "Compass + Paper"],
["Nuts", "Cones + Tools"],
["New Year Tree", "Conifers + New Year’s Baubles"],
["Polluted Earth", "Earth + Nuclear Waste"],
["Ceramics", "Fire + Potter’s Wheel"],
["Fishing Boat", "Fishing Net + Boat"],
["Sound", "Flute + Air"],
["Noria", "Grains + Water Wheel"],
["Fireworks", "Gun Powder + Bickford Fuse"],
["Elephants", "Mammals + Hose"],
["Origami", "Paper + Flowers"],
["Pump", "Pressure + Incomplete Mechanism"],
["Torch", "Resin + Straw"],
["Amber", "Resin + Water"],
["Wooden Ladder", "Rope Ladder + Wood"],
["Mechanical Clock", "Sandglass + Gear"],
["Locomobile", "Steam Engine + Cart"],
["Candy", "Sugar + Food Factory"],
["Pillow", "Textile + Down"],
["Sail", "Textile + Wind"],
["Silk Clothes", "Textile Factory + Silk"],
["Clothes", "Textile Factory + Textile"],
["Candle", "Wax + Wick"],
["Abacus", "Coins + Bones + Wood"],
["Garland", "Glowing Lightbulb + Glowing Lightbulb + Wire"],
["Candleabrum", "Candle + Bronze"],
["New Year Tree With Garland", "Conifers + Garland"],
["Mammothes", "Elephants + Cold"],
["Fish Yield", "Fishing Boat + Water"],
["Grain Elevator", "Granary + Noria"],
["Tower", "Incomplete Building + Wooden Ladder"],
["Electronic Clock", "Mechanical Clock + CuZn Battery"],
["Teddy Bear", "New Year Tree + Bear"],
["Holiday Stockings", "New Year Tree + Clothes"],
["Assembly Line", "Noria + Metals"],
["Crane", "Origami + Birds"],
["Coconut", "Palms + Nuts"],
["Jack Pump", "Pump + Oil Field"],
["Bank", "Safe + Incomplete Building"],
["Sail Boat", "Sail + Boat"],
["Note", "Sound + Paper"],
["Gas Pipeline", "Tubing + Natural Gas"],
["Oil Pipeline", "Tubing + Oil"],
["Ancient Footwear", "Wooden Fragments + Clothes"],
["Ancient Skates", "Ancient Footwear + Bones"],
["Cloven-Hoofed Animals", "Ancient Footwear + Mammals"],
["Palm Leaves Sandals", "Ancient Footwear + Palms"],
["Automated Factory", "Assembly Line + Incomplete Factory"],
["Powersaw Bench", "Assembly Line + Saw"],
["Coconut Shell", "Coconut + Stone"],
["Canning", "Fish Yield + Food Factory"],
["Gas Refinery", "Gas Pipeline + Incomplete Factory"],
["Holiday Stockings with Ash", "Holiday Stockings + Ash"],
["Holiday Stockings with Gifts", "Holiday Stockings + Candy"],
["Melody", "Note + Note"],
["Oil Refinery", "Oil Pipeline + Incomplete Factory"],
["Skis", "Snow + Ancient Footwear"],
["Clock Tower", "Tower + Mechanical Clock"],
["Lighthouse", "Tower + Search Light"],
["Watch Tower", "Tower + Spyglass"],
["Water Tower", "Tower + Draw Well + Pump"],
["Castle", "Tower + Tower + House"],
["Nonruminants", "Canines + Cloven-Hoofed Animals"],
["Cloud Castle", "Castle + Clouds"],
["Moat", "Castle + Water"],
["Ruminants", "Cloven-Hoofed Animals + Grass"],
["Activated Carbon", "Coconut Shell + Fire"],
["Coconut Milk", "Coconut Shell + Water"],
["Helium", "Gas Refinery + Natural Gas"],
["Nightingale", "Melody + Birds"],
["Musical Instruments", "Melody + Tools"],
["Benzine", "Oil + Oil Refinery"],
["Lumber Mill", "Powersaw Bench + Incomplete Building"],
["Sledge", "Skis + Cart"],
["Town", "Village + Castle"],
["Irrigation System", "Water Tower + Water Pipeline"],
["Gas Mask", "Activated Carbon + Rubber"],
["Cows", "Domestic Animals + Ruminants"],
["Star", "Helium + Hydrogen"],
["Toy Ballon", "Helium + Rubber"],
["Ballon", "Helium + Textile"],
["Deers", "Horn + Ruminants"],
["Agricultural Land", "Irrigation System + Humus"],
["Wooden Bridge", "Moat + Wooden Ladder"],
["Wild Boars", "Nonruminants + Nuts"],
["Hippopotamus", "Nonruminants + Water"],
["Giraffes", "Ruminants + Trees"],
["Internal Combustion Engine", "Steam Engine + Benzine"],
["Organ", "Musical Instruments + Tube + Tube"],
["Oat", "Agricultural Land + Cereals"],
["Pumpkin", "Agricultural Land + Grass"],
["Machine Factory", "Automated Factory + Internal Combustion Engine"],
["Airship", "Ballon + Internal Combustion Engine"],
["Milk", "Cows + Grass"],
["Reindeers", "Deers + Cold"],
["Pigs", "Domestic Animals + Wild Boars"],
["Jet Engine", "Fireworks + Internal Combustion Engine"],
["Chainsaw", "Internal Combustion Engine + Saw"],
["Star Chart", "Map + Star"],
["Astrolabe", "Mechanical Clock + Star"],
["Airplane", "Sail Plane + Internal Combustion Engine"],
["Telescope", "Spyglass + Star"],
["Sun", "Star + Earth"],
["Tea Plants", "Agricultural Land + Tropics + Shrub"],
["Cacao Tree", "Agricultural Land + Tropics + Trees"],
["Space", "Star + Star + Star"],
["Jet Airplane", "Airplane + Jet Engine"],
["Cocoa Bean", "Cacao Tree + Tools"],
["Yogurt", "Milk + Bacteria"],
["Horses", "Oat + Mammals"],
["Truffles", "Pigs + Mushrooms"],
["Jack-o-Lantern", "Pumpkin + Candle"],
["Holiday Reindeers", "Sledge + Reindeers"],
["Planishphere", "Star Chart + Astrolabe"],
["Planetarium", "Star Chart + Incomplete Building"],
["Sunflower", "Sun + Flowers"],
["Solar Panel", "Sun + ZnC Battery"],
["Tea Leaves", "Tea Plants + Tools"],
["Observatory", "Telescope + Incomplete Building"],
["Car", "Machine Factory + Metals + Rubber"],
["Ice Cream", "Milk + Sugar + Ice"],
["Citrus Plants", "Sun + Tropics + Fruits"],
["All-Terrain Vehicle", "Car + Caterpillar Platform"],
["Stagecoach", "Cart + Horses"],
["Teapot", "Ceramics + Tea Leaves"],
["Oranges", "Citrus Plants + Sugar"],
["Dark Chocolate", "Cocoa Bean + Food Factory"],
["Zebra", "Horses + Paint"],
["Sunflower Seeds", "Sunflower + Tools"],
["Lemons", "Vinegar + Citrus Plants"],
["Milk Chocolate", "Milk + Cocoa Bean + Food Factory"],
["Solar Power Plant", "Solar Panel + Solar Panel + Solar Panel"],
["Wood Transporter", "All-Terrain Vehicle + Wood"],
["Sunflower Oil", "Sunflower Seeds + Food Factory"],
["Tea", "Teapot + Fire + Water"],
["Furniture Factory", "Wood Transporter + Incomplete Factory"],
["Furniture", "Furniture Factory + Wood"],
];

let g_mapcombos = new Map();
for (let reagent of g_allcombos)
{
    g_mapcombos[reagent[0]] = reagent[1];
}

function tabs(count){
    return ("\r\n" + "-".repeat(count));
}

function expand(reagent, entrancy)
{
    if (typeof entrancy == "number") entrancy++;
    else entrancy = 0;
    if (typeof reagent == "object")
    {
        if (typeof reagent[1] == "number") return reagent[0];
        let retval = tabs(entrancy) + reagent[0] + "(";
        let subvals = reagent[1].split(" + ");
        subvals.forEach(subval => retval += expand(subval, entrancy));
        return retval + ")";
    }
    else if (typeof reagent == "string")
    {
        return expand([reagent, g_mapcombos[reagent]], entrancy);
    }
    return reagent;
}

function reduce(reagent)
{
    let retval = "";
    if (typeof reagent == "string")
    {
        let subagents = reagent.split(" + ");
        subagents.forEach(item => retval += reduce(item));
        return retval;
    }
    return reagent;
}

function printAll(combos, outputdiv)
{
    let outspew = "";
    combos.forEach(
        item => 
        {
            outspew += expand(item);
            //outspew += (item[0] + " = " + item[1] + "\r\n")
        });
    outputdiv.value += outspew;
}

